In [2]:
import numpy as np

In [10]:
#Array
arr = np.array([[0,1,2], [3,4,5]])
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
arr = np.array([0,0.1,2])
arr

array([0. , 0.1, 2. ])

In [7]:
## Copy
a = np.array([0,1])
b = np.array([9,8])

c = a

c
c[0] = 5

c
print(a)

d = b.copy()
d[0] = 10

print('Array b:{} d:{}'.format(repr(b),repr(d)))


[5 1]
Array b:array([9, 8]) d:array([10,  8])


In [ ]:
## Casting

arr = np.array()


In [5]:
arr = np.array([0,1,2])
print(arr.dtype)
arr = arr.astype(np.float32)
arr.dtype


int64


dtype('float32')

In [6]:
## NAN
arr = np.array([np.nan,1,2])
print(arr)

[nan  1.  2.]


In [7]:
arr = np.array([np.nan,'abc'])
print(repr(arr))

array(['nan', 'abc'], dtype='<U32')


In [9]:
print(np.inf > 10000000)

True


In [13]:
arr = np.array([np.inf, 5])
print(arr)

[inf  5.]


In [15]:
arr = np.array([np.nan,2,3,4,5])
arr

array([nan,  2.,  3.,  4.,  5.])

In [25]:
 # Arange

In [17]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [26]:
arr = np.arange(5.1)
arr

array([0., 1., 2., 3., 4., 5.])

In [28]:
# Linspace

In [30]:
arr = np.linspace(5,11 , num=4)
arr

array([ 5.,  7.,  9., 11.])

In [32]:
arr = np.linspace(5,11 , num=4,endpoint=False)
arr


array([5. , 6.5, 8. , 9.5])

In [35]:
arr = np.linspace(5,11 , num=4,dtype=np.int32,endpoint=False)
arr


array([5, 6, 8, 9], dtype=int32)

In [36]:
#Reshape

In [38]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [47]:
reshape_arr1 = np.reshape(arr,(2,4))
reshape_arr1

reshape_arr2 = np.reshape(arr,(-1,2,2))
print("arr:{}".format(reshape_arr1))
reshape_arr2.shape

arr:[[0 1 2 3]
 [4 5 6 7]]


(2, 2, 2)

In [7]:
arr = np.arange(8)
arr = np.reshape(arr,(2,4))
flattened = arr.flatten()
flattened

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
arr = np.arange(8)
arr = np.reshape(arr,(4,2))
print(arr)
transposed = np.transpose(arr)
transposed

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [32]:
arr = np.arange(6)
reshaped = np.reshape(arr,(3,2))
print(reshaped)
# flattened = reshaped.flatten()
# print(flattened)
transposed = np.transpose(reshaped,axes=(1,2,0))
print(transposed)

[[0 1]
 [2 3]
 [4 5]]


ValueError: axes don't match array